# Generated by Django 5.1.1 on 2024-10-27 00:06

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'reservations_area',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'reservations_customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('logo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/img'), upload_to='img/', verbose_name='Logo')),
                ('cover', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/img'), upload_to='img/', verbose_name='Cover')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'db_table': 'reservations_restaurant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Turn',
                'verbose_name_plural': 'Turns',
                'db_table': 'reservations_turn',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('opinion', models.TextField(blank=True, verbose_name='Opinion')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='reservations.customer')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'reservations_rating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(verbose_name='Table number')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Area', to='reservations.area')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'db_table': 'reservations_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TableAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.table')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.turn')),
            ],
            options={
                'verbose_name': 'Table Availability',
                'verbose_name_plural': 'Availability of Tables',
                'db_table': 'reservations_table_availability',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_guests', models.IntegerField(blank=True, verbose_name='Number of guests')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=50, verbose_name='Status')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.area')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.customer')),
                ('reservation_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.tableavailability')),
                ('reservation_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.turn')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'reservations_reservation',
                'managed': True,
            },
        ),
    ]
